services:
  backend:
    build:
      context: ./backend 
    ports:
      - "3000:3000"
    environment:
      - .env
    volumes:
      - ./backend:/app 

  frontend:
    build:
      context: ./frontend 
    ports:
      - "3001:80" 
    depends_on:
      - backend
    volumes:
      - ./frontend:/app 
